# Generated by Django 4.0.8 on 2025-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsandevents_summary_sw_ke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
    ]
