# Generated by Django 4.0.8 on 2025-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_summary_sw_ke_course_title_sw_ke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
    ]
