# Generated by Django 4.0.8 on 2025-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_choice_choice_text_sw_ke_question_content_sw_ke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_es',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
    ]
