# Generated by Django 4.0.8 on 2025-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_failedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=25, null=True),
        ),
    ]
