# Generated by Django 4.0.8 on 2025-05-05 09:18

from django.db import migrations, models
from django.db.models import Count


def clean_up_unique_student_id(apps, schema_editor):
    Student = apps.get_model('accounts', 'Student')

    # Identify duplicates
    duplicates = (
        Student.objects.values('unique_student_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    # Resolve duplicates
    for duplicate in duplicates:
        students = Student.objects.filter(unique_student_id=duplicate['unique_student_id'])
        for index, student in enumerate(students):
            if index == 0:
                # Keep the first record as is
                continue
            # Modify the duplicate records
            student.unique_student_id = f"{student.unique_student_id}-{student.id}"
            student.save()

    # Ensure all NULL values are unique
    null_students = Student.objects.filter(unique_student_id__isnull=True)
    for student in null_students:
        student.unique_student_id = f"STU-{student.id}"
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_level'),
    ]

    operations = [
        # Add the field first
        migrations.AddField(
            model_name='student',
            name='unique_student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Then clean up the data
        migrations.RunPython(clean_up_unique_student_id),
        # Finally, enforce the unique constraint
        migrations.AlterField(
            model_name='student',
            name='unique_student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]