# Generated by Django 4.0.8 on 2026-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_unique_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lecture_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
